# Generated by Django 5.1 on 2024-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='correo_usurio',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
