# Generated by Django 5.1 on 2024-08-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_remove_contenido_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('likes', models.IntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
