# Generated by Django 5.1 on 2024-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo_usurio',
            new_name='correo_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrador', 'Administrador')], default='estudiante', max_length=50),
        ),
    ]
