# Generated by Django 5.1 on 2024-08-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('imagen', models.URLField()),
                ('ano', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('materia', models.CharField(choices=[('Programacion 2', 'PROGRAMACION 2'), ('Algoritmos y estructura de Datos', 'ALGORITMOS Y ESTRUCTURA DE DATOS'), ('Base de Datos 1', 'BASE DE DATOS 1'), ('Base de Datos 2', 'BASE DE DATOS 2'), ('Programacion Orientada a Objetos', 'PROGRAMACION ORIENTADA A OBJETOS'), ('Sistemas Operativos 1', 'SISTEMAS OPERATIVOS 1'), ('Sistemas Operativos 2', 'SISTEMAS OPERATIVOS 2'), ('Lenjuajes de Programacion', 'LENGUAJES DE PROGRAMACION'), ('Electronica', 'ELECTRONICA'), ('Circuitos Electricos', 'CIRCUITOS ELECTRICOS')], max_length=100)),
            ],
        ),
    ]
